const productActionTypes = {
  FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
  FETCH_PRODUCT_FAIL: 'FETCH_PRODUCT_FAIL',
  FETCH_PRODUCT_SUCCESS_LAST: 'FETCH_PRODUCT_SUCCESS_LAST',
  FETCH_PRODUCT_SORT_SUCCESS: 'FETCH_PRODUCT_SORT_SUCCESS',
};

export default productActionTypes;
